### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by Zyin055** [Haoming02/sd-webui-i2i-ancestral-tree#1]
When clicking the populate button I get this error:

```
Traceback (most recent call last):
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 31, in populate_textfields
    t2i, t2if, i2i, i2if = parse_latest_folder()
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 12, in parse_latest_folder
    os.listdir(T2I_OUTPUT_FOLDER),
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Stuff\\AI\\SD\\shared\\outputs\\images\\outputs/txt2img-images'
```

Both my txt2img and img2img files are being saved to a non-default path (set in A1111 settings): `C:\Stuff\AI\SD\shared\outputs\images`

I tried to set the full path in the text fields but nothing seemed to work. It seems like you may be hard coding a path `outputs/txt2img-images` when you shouldn't be.

**Comment by Haoming02** [comment]
If you take a look at the [script](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/blob/main/scripts/i2i_tree.py#L8), I specifically grab the path from the user's option.

> Both my txt2img and img2img files are being saved to a non-default path (set in A1111 settings)

Was that set through the settings? Or is that commandline args? Or something else?

**Comment by Zyin055** [comment]
It's set via the A1111 settings page:

![settings](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/assets/5003647/d7838219-f1c3-4a8b-802c-3a68eae99b6b)

**Comment by Haoming02** [comment]
OK, I reproduced the error now. Give me some time to fix it.
Maybe I will just change it to a textfield instead...

In the meantime. if you want to manually enter the full path, 
- The left field should be the parent path (`C:\Stuff\AI\SD\shared\outputs\images`)
- The right field should be the folder that contains the images (**eg.** `2024-01-04`)

**Comment by Zyin055** [comment]
> The right field should be the folder that contains the images (eg. 2024-01-04)

I also have the setting enabled where it doesn't make folders with the current date - they're all just in one big folder. Not sure if that'll be a problem or not.

**Comment by Haoming02** [comment]
Wait, so both your `txt2img` and `img2img` results all get put in the same giant folder?

**Comment by Zyin055** [comment]
Yup.

**Comment by Haoming02** [comment]
Ah OK. Guess I will really just make it a textfield that user can enter the full path...
~~Working with customizable path is pain~~

If you still want to try right now, set the left field to `C:\Stuff\AI\SD\shared\outputs` and the right field to `images` I guess.
Though, if the folder contains many images, it will probably take a significant amount of time...
And I never tried setting the `txt2img` path and the `img2img` path to the same folder, not sure if this will create duplicates or not...

**Comment by Zyin055** [comment]
![Clipboard01](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/assets/5003647/df48438b-a303-4c26-b134-6d98a0322815)

```
Traceback (most recent call last):
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 31, in populate_textfields
    t2i, t2if, i2i, i2if = parse_latest_folder()
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 12, in parse_latest_folder
    os.listdir(T2I_OUTPUT_FOLDER),
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Stuff\\AI\\SD\\shared\\outputs\\images\\outputs/txt2img-images'
```

**Comment by Haoming02** [comment]
Oh, **Populate** is only for filling out the fields.
If you already enter the fields, just click **Load**.

**Comment by Zyin055** [comment]
Looks like it's trying to load a folder too deep. Every 50k images I put them in a subfolder for storage (the `1-49999` named folder in this error message).

```
Traceback (most recent call last):
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 54, in load_images
    return [
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 55, in <listcomp>
    (img, f'{img}_-{path2hash(img)}_-{img2input(img)}') for img in image_files
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_info.py", line 10, in path2hash
    return img2hash(Image.open(path))
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\Stuff\\AI\\SD\\shared\\outputs\\images\\1-49999'
```

**Comment by Haoming02** [comment]
~~You said there is no subfolder~~

Put `C:\\Stuff\\AI\\SD\\shared\\outputs\\images` in the left field;
put `1-49999` in the right field.

**Comment by Zyin055** [comment]
Click Load button:
```
Traceback (most recent call last):
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 54, in load_images
    return [
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 55, in <listcomp>
    (img, f'{img}_-{path2hash(img)}_-{img2input(img)}') for img in image_files
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_info.py", line 13, in img2input
    params = Image.open(path).info['parameters'].split(',')
KeyError: 'parameters'
```
This isn't an extension I desperately need working, so if you want to fix these bugs then you should probably just configure your settings like mine and fix the errors that way.

**Comment by Haoming02** [comment]
Clicking **Populate** should fill out `C:\Stuff\AI\SD\shared\outputs\images` for you now.

Though, right now it will only process the parent folder, not the sub-folders (`1-49999`).

I will add a recursive checkbox later.

**Comment by Haoming02** [comment]
> params = Image.open(path).info['parameters'].split(',')
> KeyError: 'parameters'

Hmm. Did you disable the `Infotex` metadata for your images?

**Comment by Zyin055** [comment]
Using vanilla infotext settings.

![settings](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/assets/5003647/071e9987-f24d-4858-a522-97f01560ae6b)

**Comment by Haoming02** [comment]
Inside the folders, do you have non-generated-results files?

**Comment by Zyin055** [comment]
1-49999 does not. only my `C:\Stuff\AI\SD\shared\outputs\images` directory does, which is where my new images go.

**Comment by Haoming02** [comment]
Huh. Then why does the image not have `parameters` info ._.

**Comment by Zyin055** [comment]
Oh, some of the images in 1-49999 probably don't. That's back when I had the infotext saved in a .txt file.

**Comment by Haoming02** [comment]
OK, I'll also add a check for that.
Thanks for the reminder.

**Comment by Haoming02** [comment]
With the latest commit, it should now:
- Check for a `.txt` when an image does not contain the metadata
- If a `.txt` is still not found, the image is simply skipped
- Being able to enable **Recursive Search** to load all images under a folder

Though, if you load like 50k images at the same time, it will probably take an hour to process XD

**Comment by Zyin055** [comment]
Pulled the latest commit. I moved some images into a separate folder that I did some inpainting on. Pasted the folder's path into the new big text field and click Generate and it says "Hmm... No images detected...". Then reloaded the UI and tried again, this time no error in console but nothing happens.

**Comment by Haoming02** [comment]
> some images into a separate folder that I did some inpainting on

Were those generated from each others? Cause for images whose parent is not found, or images which was not dependent on, the graph ignores them.

**Comment by Zyin055** [comment]
Yes, there's a single txt2img .jpg in there and multiple img2img inpaint .jpgs stemming from it. Also some images that were edited with GIMP, and a .xcf file (GIMP).

Tried again and now this:

```
Traceback (most recent call last):
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_tree.py", line 59, in load_images
    img_list.append((img, f'{img}_-{path2hash(img)}_-{img2input(img)}'))
  File "C:\Stuff\AI\SD\stable-diffusion-webui-1.7\extensions\sd-webui-i2i-ancestral-tree\scripts\i2i_info.py", line 13, in img2input
KeyError: 'parameters'
```

**Comment by Haoming02** [comment]
> KeyError: 'parameters'

Try close and restart the entire Webui first. `ReloadUI` sometimes does not actually reload all the scripts.

**Comment by Zyin055** [comment]
Did a full restart, still nothing happens and no messages in console when using the outside folder's path.

Tried again with the auto generated Populate path and it kept my ssd busy for 8 minutes as it scanned 16k images. Nothing happened after it finished, no errors, no messages, no image trees.

I'm not going to bother debugging this anymore, I might check back after some updates to see if you get this all sorted out.

**Comment by Haoming02** [comment]
> there's a single txt2img .jpg in there and multiple img2img inpaint .jpgs stemming from it

Can you send those files so I can test it myself?

**Comment by Haoming02** [comment]
> `.jpg`

Ah, so that's the problem... The metadata of `.jpg` is encoded...

**Comment by Haoming02** [comment]
I'm now using the Webui's built-in `read_info_from_image`.
It should at least work for:
- `.jpg` with exif
- `.png` with metadata
- `.jpg` with external `.txt`
- `.png` with external `.txt`

**Comment by Haoming02** [comment]
![01](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/assets/73768377/ee316fc4-cdb9-4e8d-b789-bfc7eb498484)

![02](https://github.com/Haoming02/sd-webui-i2i-ancestral-tree/assets/73768377/ecea8363-119d-4002-9009-d515e82344af)

**Comment by Haoming02** [comment]
Many thanks for testing out the Extension back then~
